package org.openmrs.module.hydra.model.workflow;

// Generated Jul 19, 2019 12:33:37 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.openmrs.BaseOpenmrsMetadata;
import org.openmrs.Concept;

/**
 * HydramoduleComponent generated by hbm2java
 */
@Entity
@Table(name = "hydramodule_component", catalog = "hydra")
public class HydramoduleComponent extends BaseOpenmrsMetadata implements java.io.Serializable {

	private static final long serialVersionUID = 1969581011447190685L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "component_id", unique = true, nullable = false)
	private Integer componentId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "concept_id")
	private Concept concept;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hydramoduleComponent")
	private Set<HydramodulePhaseComponents> hydramodulePhaseComponentses = new HashSet<HydramodulePhaseComponents>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hydramoduleComponent")
	private Set<HydramoduleComponentForms> hydramoduleComponentFormses = new HashSet<HydramoduleComponentForms>(0);

	public HydramoduleComponent() {
	}

	public Integer getComponentId() {
		return this.componentId;
	}

	public void setComponentId(Integer componentId) {
		this.componentId = componentId;
	}

	public Concept getConcept() {
		return this.concept;
	}

	public void setConcept(Concept concept) {
		this.concept = concept;
	}

	public Set<HydramodulePhaseComponents> getHydramodulePhaseComponentses() {
		return this.hydramodulePhaseComponentses;
	}

	public void setHydramodulePhaseComponentses(Set<HydramodulePhaseComponents> hydramodulePhaseComponentses) {
		this.hydramodulePhaseComponentses = hydramodulePhaseComponentses;
	}

	public Set<HydramoduleComponentForms> getHydramoduleComponentFormses() {
		return this.hydramoduleComponentFormses;
	}

	public void setHydramoduleComponentFormses(Set<HydramoduleComponentForms> hydramoduleComponentFormses) {
		this.hydramoduleComponentFormses = hydramoduleComponentFormses;
	}

	@Override
	public Integer getId() {
		return componentId;
	}

	@Override
	public void setId(Integer id) {
		this.componentId = id;
	}

}
