package org.openmrs.module.hydra.model.workflow;
// Generated Jul 19, 2019 12:33:37 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.openmrs.BaseOpenmrsMetadata;
import org.openmrs.Concept;
import org.openmrs.User;

/**
 * HydramoduleWorkflow generated by hbm2java
 */
@Entity
@Table(name = "hydramodule_workflow", catalog = "hydra")
public class HydramoduleWorkflow extends BaseOpenmrsMetadata implements java.io.Serializable {

	private static final long serialVersionUID = 4608951679859347816L;

	private Integer workflowId;
	private Concept concept;
	private String name;
	private Set hydramoduleWorkflowPhaseses = new HashSet(0);

	public HydramoduleWorkflow() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "workflow_id", unique = true, nullable = false)
	public Integer getWorkflowId() {
		return this.workflowId;
	}

	public void setWorkflowId(Integer workflowId) {
		this.workflowId = workflowId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "concept_id")
	public Concept getConcept() {
		return this.concept;
	}

	public void setConcept(Concept concept) {
		this.concept = concept;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hydramoduleWorkflow")
	public Set getHydramoduleWorkflowPhaseses() {
		return this.hydramoduleWorkflowPhaseses;
	}

	public void setHydramoduleWorkflowPhaseses(Set hydramoduleWorkflowPhaseses) {
		this.hydramoduleWorkflowPhaseses = hydramoduleWorkflowPhaseses;
	}

	@Override
	public Integer getId() {
		return workflowId;
	}

	@Override
	public void setId(Integer id) {
		this.workflowId = id;
	}

}
