package org.openmrs.module.hydra.model.workflow;

// Generated Jul 19, 2019 12:33:37 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HydramoduleWorkflowPhases generated by hbm2java
 */
@Entity
@Table(name = "hydramodule_workflow_phases", catalog = "hydra")
public class HydramoduleWorkflowPhases implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer id;

	private HydramodulePhase hydramodulePhase;

	private HydramoduleWorkflow hydramoduleWorkflow;

	public HydramoduleWorkflowPhases() {
	}

	public HydramoduleWorkflowPhases(HydramodulePhase hydramodulePhase, HydramoduleWorkflow hydramoduleWorkflow) {
		this.hydramodulePhase = hydramodulePhase;
		this.hydramoduleWorkflow = hydramoduleWorkflow;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "phase_id", nullable = false)
	public HydramodulePhase getHydramodulePhase() {
		return this.hydramodulePhase;
	}

	public void setHydramodulePhase(HydramodulePhase hydramodulePhase) {
		this.hydramodulePhase = hydramodulePhase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "workflow_id", nullable = false)
	public HydramoduleWorkflow getHydramoduleWorkflow() {
		return this.hydramoduleWorkflow;
	}

	public void setHydramoduleWorkflow(HydramoduleWorkflow hydramoduleWorkflow) {
		this.hydramoduleWorkflow = hydramoduleWorkflow;
	}

}
