package org.openmrs.module.hydra.model.workflow;

// Generated Jul 19, 2019 12:33:37 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.annotate.JsonManagedReference;
import org.openmrs.BaseOpenmrsMetadata;
import org.openmrs.Form;
import org.openmrs.Program;

/**
 * HydramoduleForm generated by hbm2java
 */
@Entity
@Table(name = "hydramodule_form", catalog = "hydra", uniqueConstraints = @UniqueConstraint(columnNames = "uuid"))
public class HydramoduleForm extends BaseOpenmrsMetadata implements java.io.Serializable {

	private static final long serialVersionUID = -2668916537478185182L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "hydramodule_form_id", unique = true, nullable = false)
	private Integer hydramoduleFormId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "form_id")
	private Form form;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "program_id")
	private Program program;

	@Column(name = "actions_xml", length = 2000)
	private String actionsXml;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hydramoduleForm")
	@JsonManagedReference
	private Set<HydramoduleFormTagMap> hydramoduleFormTagMaps = new HashSet<HydramoduleFormTagMap>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hydramoduleForm")
	@JsonIgnore
	private Set<HydramoduleComponentForms> hydramoduleComponentFormses = new HashSet<HydramoduleComponentForms>(0);

	public HydramoduleForm() {
	}

	public Integer getHydramoduleFormId() {
		return this.hydramoduleFormId;
	}

	public void setHydramoduleFormId(Integer hydramoduleFormId) {
		this.hydramoduleFormId = hydramoduleFormId;
	}

	public Form getForm() {
		return this.form;
	}

	public void setForm(Form form) {
		this.form = form;
	}

	public Program getProgram() {
		return this.program;
	}

	public void setProgram(Program program) {
		this.program = program;
	}

	public String getActionsXml() {
		return this.actionsXml;
	}

	public void setActionsXml(String actionsXml) {
		this.actionsXml = actionsXml;
	}

	public Set<HydramoduleFormTagMap> getHydramoduleFormTagMaps() {
		return this.hydramoduleFormTagMaps;
	}

	public void setHydramoduleFormTagMaps(Set<HydramoduleFormTagMap> hydramoduleFormTagMaps) {
		this.hydramoduleFormTagMaps = hydramoduleFormTagMaps;
	}

	public Set<HydramoduleComponentForms> getHydramoduleComponentFormses() {
		return this.hydramoduleComponentFormses;
	}

	public void setHydramoduleComponentFormses(Set<HydramoduleComponentForms> hydramoduleComponentFormses) {
		this.hydramoduleComponentFormses = hydramoduleComponentFormses;
	}

	@Override
	public Integer getId() {
		return hydramoduleFormId;
	}

	@Override
	public void setId(Integer id) {
		this.hydramoduleFormId = id;
	}

}
