package org.openmrs.module.hydra.model.workflow;

// Generated Jul 19, 2019 12:33:37 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonBackReference;

/**
 * HydramoduleFormTagMap generated by hbm2java
 */
@Entity
@Table(name = "hydramodule_form_tag_map", catalog = "hydra")
public class HydramoduleFormTagMap implements java.io.Serializable {

	private static final long serialVersionUID = -5939617019084047405L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hydramodule_form_id", nullable = false)
	@JsonBackReference
	private HydramoduleForm hydramoduleForm;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "form_tag_id", nullable = false)
	private HydramoduleFormTag hydramoduleFormTag;

	public HydramoduleFormTagMap() {
	}

	public HydramoduleFormTagMap(HydramoduleForm hydramoduleForm, HydramoduleFormTag hydramoduleFormTag) {
		this.hydramoduleForm = hydramoduleForm;
		this.hydramoduleFormTag = hydramoduleFormTag;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public HydramoduleForm getHydramoduleForm() {
		return this.hydramoduleForm;
	}

	public void setHydramoduleForm(HydramoduleForm hydramoduleForm) {
		this.hydramoduleForm = hydramoduleForm;
	}

	public HydramoduleFormTag getHydramoduleFormTag() {
		return this.hydramoduleFormTag;
	}

	public void setHydramoduleFormTag(HydramoduleFormTag hydramoduleFormTag) {
		this.hydramoduleFormTag = hydramoduleFormTag;
	}

}
