package org.openmrs.module.hydra.model.workflow;
// Generated Jul 19, 2019 12:33:37 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.openmrs.BaseOpenmrsMetadata;
import org.openmrs.Form;
import org.openmrs.Program;

/**
 * HydramoduleForm generated by hbm2java
 */
@Entity
@Table(name = "hydramodule_form", catalog = "hydra", uniqueConstraints = @UniqueConstraint(columnNames = "uuid"))
public class HydramoduleForm extends BaseOpenmrsMetadata implements java.io.Serializable {

	private Integer hydramoduleFormId;
	private Form form;
	private Program program;
	private String actionsXml;
	private Set hydramoduleFormTagMaps = new HashSet(0);
	private Set hydramoduleComponentFormses = new HashSet(0);

	public HydramoduleForm() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "hydramodule_form_id", unique = true, nullable = false)
	public Integer getHydramoduleFormId() {
		return this.hydramoduleFormId;
	}

	public void setHydramoduleFormId(Integer hydramoduleFormId) {
		this.hydramoduleFormId = hydramoduleFormId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "form_id")
	public Form getForm() {
		return this.form;
	}

	public void setForm(Form form) {
		this.form = form;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "program_id")
	public Program getProgram() {
		return this.program;
	}

	public void setProgram(Program program) {
		this.program = program;
	}

	@Column(name = "actions_xml", length = 2000)
	public String getActionsXml() {
		return this.actionsXml;
	}

	public void setActionsXml(String actionsXml) {
		this.actionsXml = actionsXml;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hydramoduleForm")
	public Set getHydramoduleFormTagMaps() {
		return this.hydramoduleFormTagMaps;
	}

	public void setHydramoduleFormTagMaps(Set hydramoduleFormTagMaps) {
		this.hydramoduleFormTagMaps = hydramoduleFormTagMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hydramoduleForm")
	public Set getHydramoduleComponentFormses() {
		return this.hydramoduleComponentFormses;
	}

	public void setHydramoduleComponentFormses(Set hydramoduleComponentFormses) {
		this.hydramoduleComponentFormses = hydramoduleComponentFormses;
	}

	@Override
	public Integer getId() {
		return hydramoduleFormId;
	}

	@Override
	public void setId(Integer id) {
		this.hydramoduleFormId = id;
	}

}
