package org.openmrs.module.hydra.model.workflow;
// Generated Jul 19, 2019 12:33:37 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HydramodulePhaseComponents generated by hbm2java
 */
@Entity
@Table(name="hydramodule_phase_components"
    ,catalog="hydra"
)
public class HydramodulePhaseComponents  implements java.io.Serializable {


     private Integer id;
     private HydramoduleComponent hydramoduleComponent;
     private HydramodulePhase hydramodulePhase;

    public HydramodulePhaseComponents() {
    }

    public HydramodulePhaseComponents(HydramoduleComponent hydramoduleComponent, HydramodulePhase hydramodulePhase) {
       this.hydramoduleComponent = hydramoduleComponent;
       this.hydramodulePhase = hydramodulePhase;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="component_id", nullable=false)
    public HydramoduleComponent getHydramoduleComponent() {
        return this.hydramoduleComponent;
    }
    
    public void setHydramoduleComponent(HydramoduleComponent hydramoduleComponent) {
        this.hydramoduleComponent = hydramoduleComponent;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="phase_id", nullable=false)
    public HydramodulePhase getHydramodulePhase() {
        return this.hydramodulePhase;
    }
    
    public void setHydramodulePhase(HydramodulePhase hydramodulePhase) {
        this.hydramodulePhase = hydramodulePhase;
    }




}


