package org.openmrs.module.hydra.model.workflow;

// Generated Jul 19, 2019 12:33:37 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonBackReference;
import org.openmrs.BaseOpenmrsData;
import org.openmrs.BaseOpenmrsMetadata;
import org.openmrs.BaseOpenmrsObject;

/**
 * HydramoduleComponentForms generated by hbm2java
 */
@Entity
@Table(name = "hydramodule_component_forms", catalog = "hydra")
public class HydramoduleComponentForms extends BaseOpenmrsObject implements java.io.Serializable {

	private static final long serialVersionUID = 5949471417426993376L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "component_id", nullable = false)
	@JsonBackReference
	private HydramoduleComponent hydramoduleComponent;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hydra_form_id", nullable = false)
	private HydramoduleForm hydramoduleForm;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "workflow_id", nullable = false)
	@JsonBackReference
	private HydramoduleWorkflow hydramoduleWorkflow;

	@Column(name = "display_order")
	private int displayOrder;

	public int getDisplayOrder() {
		return displayOrder;
	}

	public void setDisplayOrder(int displayOrder) {
		this.displayOrder = displayOrder;
	}

	public HydramoduleComponentForms() {
	}

	public HydramoduleComponentForms(HydramoduleComponent hydramoduleComponent, HydramoduleForm hydramoduleForm) {
		this.hydramoduleComponent = hydramoduleComponent;
		this.hydramoduleForm = hydramoduleForm;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public HydramoduleComponent getHydramoduleComponent() {
		return this.hydramoduleComponent;
	}

	public void setHydramoduleComponent(HydramoduleComponent hydramoduleComponent) {
		this.hydramoduleComponent = hydramoduleComponent;
	}

	public HydramoduleForm getHydramoduleForm() {
		return this.hydramoduleForm;
	}

	public void setHydramoduleForm(HydramoduleForm hydramoduleForm) {
		this.hydramoduleForm = hydramoduleForm;
	}

	public HydramoduleWorkflow getHydramoduleWorkflow() {
		return this.hydramoduleWorkflow;
	}

	public void setHydramoduleWorkflow(HydramoduleWorkflow hydramoduleWorkflow) {
		this.hydramoduleWorkflow = hydramoduleWorkflow;
	}

}
