package org.openmrs.module.hydra.model.workflow;
// Generated Jul 19, 2019 12:33:37 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.openmrs.BaseOpenmrsData;

/**
 * HydramoduleComponentForms generated by hbm2java
 */
@Entity
@Table(name = "hydramodule_component_forms", catalog = "hydra")
public class HydramoduleComponentForms extends BaseOpenmrsData implements java.io.Serializable {
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	private HydramoduleComponent hydramoduleComponent;
	private HydramoduleForm hydramoduleForm;

	public HydramoduleComponentForms() {
	}

	public HydramoduleComponentForms(HydramoduleComponent hydramoduleComponent, HydramoduleForm hydramoduleForm) {
		this.hydramoduleComponent = hydramoduleComponent;
		this.hydramoduleForm = hydramoduleForm;
	}

	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "component_id", nullable = false)
	public HydramoduleComponent getHydramoduleComponent() {
		return this.hydramoduleComponent;
	}

	public void setHydramoduleComponent(HydramoduleComponent hydramoduleComponent) {
		this.hydramoduleComponent = hydramoduleComponent;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hydra_form_id", nullable = false)
	public HydramoduleForm getHydramoduleForm() {
		return this.hydramoduleForm;
	}

	public void setHydramoduleForm(HydramoduleForm hydramoduleForm) {
		this.hydramoduleForm = hydramoduleForm;
	}

}
